### ISSUE TITLE
Path /pv-disks/dev is not an actual mountpoint

### ISSUE THREAD

**Issue by motizzz** [brunsgaard/eks-nvme-ssd-provisioner#15]
Hi 

EC2 instance: i3en.6xlarge

I'm trying to run this in AWS EKS using the yaml files from the manifests dir, and i see this error msg in the local-volume-provisioner app logs:  
`
discovery.go:301] Path "/pv-disks/dev" is not an actual mountpoint
`

eks-nvme-ssd-provisioner logs show: 

```
Volumes already present in "/pv-disks"

drwxr-xr-x    3 root     root            26 Jan 10 13:45 dev

I assume that provisioning already happend, doing nothing!
```

what i missing ?

**Comment by brunsgaard** [comment]
I dont have a good answer for you, it is strange that your disk is called `dev` normally I think they get UUID names. It has been a year since I used this project last time. If you figure it out, please let me know, but it is on you to debug, I can not help further. Hope you figure it out.

**Comment by bhuddlestonocl** [comment]
Hello, it appears Amazon has been provisioning some nodes with `/pv-disks/dev`. This causes the scripts to not attempt any provisioning. I found refactoring the script to target `/pv-disks/disks` and mounting that path instead to fix the issue.

**Comment by gricey432** [comment]
@bhuddlestonocl could you submit your changes as a PR? Or some other way to share the required changes

I'm getting this same error. I'm using a self-hosted image built from Dockerfile in master

**Comment by bhuddlestonocl** [comment]
> @bhuddlestonocl could you submit your changes as a PR? Or some other way to share the required changes
> 
> I'm getting this same error. I'm using a self-hosted image built from Dockerfile in master

Here are my changes: https://github.com/brunsgaard/eks-nvme-ssd-provisioner/compare/master...bhuddlestonocl:master

I haven't validated that this isn't just an edge-case for our specific AMI, so I'm not going to make a PR of this quite yet.

**Comment by gricey432** [comment]
> Here are my changes: [master...bhuddlestonocl:master](https://github.com/brunsgaard/eks-nvme-ssd-provisioner/compare/master...bhuddlestonocl:master)

Appreciate it, I made similar changes and this started working for me.

> I haven't validated that this isn't just an edge-case for our specific AMI, so I'm not going to make a PR of this quite yet.

For reference, I'm using `AL2_x86_64 1.22.9-20220610`
