### ISSUE TITLE
Not compatible with Kubernetes 1.16

### ISSUE THREAD

**Issue by gensym-x** [brunsgaard/eks-nvme-ssd-provisioner#2]
The extensions/v1beta1 API is no longer served in Kubernetes 1.16 (available on AWS EKS). "apps/v1" replaces it.

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

On my EKS cluster (v 1.16) eks-nvme-ssd-provisioner would not deploy until the manifest was updated. The local-storage-provisioner manifest already uses the newer API and would deploy without issue.

**Comment by brunsgaard** [comment]
I will take a look at this issue within a couple of days. Thank you for reporting it.

**Comment by brunsgaard** [comment]
fixed
