### ISSUE TITLE
alpine image does not set uuid properly in script

### ISSUE THREAD

**Issue by bhops** [brunsgaard/eks-nvme-ssd-provisioner#6]
It looks like the alpine version of this image uses a broken version of `blkid`, which does not respect the `-o` flag.
This results in `$UUID` being set to the full output of `blkid` which is not valid for the later commands.

See https://gitlab.alpinelinux.org/alpine/aports/-/issues/11404 for more information.

This appears to be resolved by adding `blkid` to the `apk add` instructions in the Dockerfile.

**Comment by brunsgaard** [comment]
fixed with #7
